function csvEscape(val: unknown): string {
  const s = String(val ?? "");
  return s.includes(",") || s.includes('"') || s.includes("\n") ? `"${s.replace(/"/g, '""')}"` : s;
}

export function downloadCSV(filename: string, headers: string[], rows: unknown[][]): void {
  const csv = [headers, ...rows].map((r) => r.map(csvEscape).join(",")).join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadExcel(filename: string, title: string, headers: string[], rows: unknown[][]): void {
  const tableRows = rows.map((r) =>
    `<tr>${r.map((c) => `<td style="padding:8px 12px;border:1px solid #e5e7eb;font-size:12px">${csvEscape(c)}</td>`).join("")}</tr>`
  ).join("\n");
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title>
    <style>
      body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 20px; }
      h2 { color: #0D9488; margin-bottom: 16px; }
      table { border-collapse: collapse; width: 100%; }
      th { background: #0D9488; color: white; padding: 10px 12px; text-align: left; font-weight: 600; font-size: 12px; border: 1px solid #0D9488; }
      td { padding: 8px 12px; border: 1px solid #e5e7eb; font-size: 12px; }
      tr:nth-child(even) { background: #f9fafb; }
      tr:hover { background: #f0fdfa; }
    </style>
  </head><body>
    <h2>${title}</h2>
    <table>
      <thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
    <p style="font-size:10px;color:#9ca3af;margin-top:16px">Generated by Faraz Pharmacy POS</p>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        const table = document.querySelector('table');
        let tsv = '';
        const rows = table.querySelectorAll('tr');
        rows.forEach(function(row) {
          const cells = row.querySelectorAll('th, td');
          const rowData = [];
          cells.forEach(function(cell) { rowData.push(cell.textContent || ''); });
          tsv += rowData.join('\\t') + '\\n';
        });
        const btn = document.createElement('button');
        btn.textContent = 'Copy to Clipboard (paste into Excel)';
        btn.style.cssText = 'position:fixed;top:20px;right:20px;padding:12px 24px;background:#0D9488;color:white;border:none;border-radius:8px;font-size:14px;cursor:pointer;z-index:9999;box-shadow:0 2px 8px rgba(0,0,0,0.15);';
        btn.onclick = function() {
          navigator.clipboard.writeText(tsv).then(function() {
            btn.textContent = 'Copied!';
            setTimeout(function() { btn.textContent = 'Copy to Clipboard (paste into Excel)'; }, 2000);
          });
        };
        document.body.appendChild(btn);
      });
    <\/script>
  </body></html>`;
  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

export function downloadPDF(filename: string, title: string, headers: string[], rows: unknown[][]): void {
  const tableRows = rows.map((r) =>
    `<tr>${r.map((c) => `<td style="padding:6px 10px;border:1px solid #ccc;font-size:12px">${csvEscape(c)}</td>`).join("")}</tr>`
  ).join("\n");
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${title}</title></head><body>
    <h2 style="font-family:sans-serif;margin-bottom:16px">${title}</h2>
    <table style="border-collapse:collapse;width:100%;font-family:sans-serif">
      <thead><tr>${headers.map((h) => `<th style="padding:8px 10px;border:1px solid #999;background:#eee;font-size:13px;text-align:left">${h}</th>`).join("")}</tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
    <p style="font-family:sans-serif;font-size:10px;color:#888;margin-top:16px">Generated by Faraz Pharmacy POS</p>
    <script>window.print()<\/script>
  </body></html>`;
  const win = window.open("", "_blank");
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}